name: mobile_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  uuid: ^4.4.0
  logger: ^2.2.0
  fluttertoast: ^8.2.5
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.3
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
